apiVersion: apps/v1 # Kubernetes API version
kind: Deployment
metadata:
  name: hello-world-deployment
  namespace: hello-world
spec:
  selector:
    matchLabels:
      app: hello-world
  replicas: 1 # tells deployment to run n pods matching the template
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: tjaard123/hello-world:1.0
        ports:
        - containerPort: 80