replicaCount: 1

image:
  repository: tjaard123/hello-world
  tag: "1.0"
  pullPolicy: Always

nameOverride: "hello-world"
fullnameOverride: "hello-world "

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {
    kubernetes.io/ingress.class: nginx
  }
  path: /
  hosts:
    - lala.io
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
